Task3_Creating basic server
PrKsushka/Node_JS_Lab pull request #1
Opened 2022-01-27 19:47 UTC by PrKsushka

2022-01-31 10:29 UTC, derkach-artem requested changes

2022-01-31 10:29 UTC, derkach-artem commented on server.js
> +    const url=req.url;
const { url, method } = req

2022-02-01 08:48 UTC, PrKsushka commented on server.js
> +    const url=req.url;
Исправила

2022-02-01 09:57 UTC, derkach-artem approved these changes

2022-02-01 10:57 UTC, merged