Task5_Using database
PrKsushka/Node_JS_Lab pull request #3
Opened 2022-01-28 16:20 UTC by PrKsushka

2022-01-31 10:48 UTC, derkach-artem requested changes

2022-01-31 10:48 UTC, derkach-artem commented on db/controller/product/dataAboutProducts.js
> +        res.json(products);
если ты добавила статус в ошибку, почему бы при успешном явно не ставить статус ..... для однообразия )

2022-01-31 10:48 UTC, derkach-artem commented on db/models/product.js
> +const Product=mongoose.model("products", productSchema);
![image](https://user-images.githubusercontent.com/24730289/151779989-864dd02e-3797-417f-9209-a48929b9b478.png)
products - нужно с большой буквы

2022-01-31 10:48 UTC, derkach-artem commented on oldServers/server.js
> +const PORT=3000;
Если добавила .env, то подобные переменные нужно вынести в этот конфиг

2022-01-31 10:48 UTC, derkach-artem commented on oldServers/server.js
> +const PORT=3000;
PS. Креды от БД туда же

2022-02-01 08:52 UTC, PrKsushka commented on db/models/product.js
> +const Product=mongoose.model("products", productSchema);
Исправила

2022-02-01 08:54 UTC, PrKsushka commented on oldServers/server.js
> +const PORT=3000;
Исправила

2022-02-01 09:03 UTC, PrKsushka commented on db/controller/product/dataAboutProducts.js
> +        res.json(products);
Исправила

2022-02-01 09:56 UTC, derkach-artem approved these changes

2022-02-01 09:56 UTC, derkach-artem commented on .env
> +PORT=3000
DB_NAME='gameStore'
DB_PASS='111111111'
`mongodb+srv://ksushka:${process.env.DB_PASS}@shop.rtbtb.mongodb.net/${process.env.DB_NAME}?retryWrites=true&w=majority`

2022-02-01 09:56 UTC, derkach-artem commented on oldServers/server.js
> +const PORT=process.env.PORT;
Это перемести на 27 строку

2022-02-01 10:05 UTC, PrKsushka commented on .env
> +PORT=3000
Исправила

2022-02-01 10:05 UTC, PrKsushka commented on oldServers/server.js
> +const PORT=process.env.PORT;
Исправила

2022-02-01 10:41 UTC, derkach-artem approved these changes

2022-02-01 11:09 UTC, merged